# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lost_games',
            field=models.IntegerField(default=0, verbose_name='Games (lost)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lost_tournaments',
            field=models.IntegerField(default=0, verbose_name='Tournaments (lost)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Scores'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='won_games',
            field=models.IntegerField(default=0, verbose_name='Games (won)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='won_tournaments',
            field=models.IntegerField(default=0, verbose_name='Tournaments (won)'),
        ),
    ]
