# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20161128_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Icon')),
                ('name', models.CharField(default='', max_length=128, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('expression', models.CharField(default='', help_text="A piece of code used for checking if achievement is unlocked. User profile is exposed as 'user' variable.", max_length=255, verbose_name='Expression')),
            ],
        ),
    ]
