# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128, verbose_name='Session ID')),
                ('phrase', models.CharField(max_length=128, verbose_name='Phrase')),
                ('progress', models.CharField(max_length=128, verbose_name='Progress')),
                ('used_characters', models.CharField(max_length=128, verbose_name='Used letters')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('mistakes', models.IntegerField(default=0, verbose_name='Mistakes')),
            ],
        ),
    ]
