# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='inverse_death',
            field=models.BooleanField(default=False, verbose_name='Inverse death'),
        ),
        migrations.AddField(
            model_name='game',
            name='max_mistakes',
            field=models.IntegerField(default=5, verbose_name='Max mistakes'),
        ),
    ]
