# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_auto_20161129_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('context', models.CharField(max_length=255, verbose_name='Context')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='admin',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='round',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='current_round',
            field=models.IntegerField(default=0, verbose_name='Current round'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='mode',
            field=models.IntegerField(default=0, verbose_name='Game mode'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_mode',
            field=models.IntegerField(default=0, verbose_name='Tournament mode'),
        ),
    ]
