# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170103_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='inverse_death',
        ),
        migrations.RemoveField(
            model_name='game',
            name='max_mistakes',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_mode',
        ),
        migrations.AddField(
            model_name='game',
            name='modifiers',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Modifiers'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='modifiers',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Modifiers'),
        ),
    ]
