# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170109_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='modifiers',
            field=models.CharField(default='', max_length=256, verbose_name='Modifiers'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='modifiers',
            field=models.CharField(default='', max_length=256, verbose_name='Modifiers'),
        ),
    ]
