# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20170110_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Time'),
        ),
    ]
