# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-07 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_chatmessage_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Is public?'),
        ),
    ]
