# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-13 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20180413_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='modifiers',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Modifiers'),
        ),
    ]
